name: tavrix_menu_mobile
description: "Flutter app foundation for Tavrix Menu business owners, managers, and staff."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
